
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://holuppwejzcqwrbdbgkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvbHVwcHdlanpjcXdyYmRiZ2tmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDQwMDQsImV4cCI6MjA2NDYyMDAwNH0.3BGIddubCa_P3fO2MJDu12j1kASJnrDrhKD92jCqR-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
